`ifndef SOFTMAX_DEFINE_VH
`define SOFTMAX_DEFINE_VH

`ifndef SOFTMAX_ROW_LEN
`define SOFTMAX_ROW_LEN 512
`endif

`ifndef SOFTMAX_BLOCK_SIZE
`define SOFTMAX_BLOCK_SIZE 8
`endif

`ifndef SOFTMAX_USE_TSMC90_SLOT_SRAM
`define SOFTMAX_USE_TSMC90_SLOT_SRAM 0
`endif

`ifndef SOFTMAX_SLOT_CTRL_MACRO
`define SOFTMAX_SLOT_CTRL_MACRO SLOT256X16_M8
`endif

`ifndef SOFTMAX_SLOT_DATA_MACRO
`define SOFTMAX_SLOT_DATA_MACRO SLOT256X36_M8
`endif

`define SOFTMAX_FP16_W       16
`define SOFTMAX_Y_W          16
`define SOFTMAX_Y_FRAC_W     10
`define SOFTMAX_M_W          7
`define SOFTMAX_DESC_W       9
`define SOFTMAX_DESC_FRAC_W  7
`define SOFTMAX_DESC_SHIFT_W 2
`define SOFTMAX_EXP_FRAC_W   7
`define SOFTMAX_SUM_FRAC_W   7
`define SOFTMAX_SUM_GLOBAL_W 16
`define SOFTMAX_OUT_W        16
`define SOFTMAX_EXP_W        (`SOFTMAX_EXP_FRAC_W + 1)
`define SOFTMAX_OUT_FRAC_W   (`SOFTMAX_OUT_W - 1)
`define SOFTMAX_OUT_SHIFT    (`SOFTMAX_OUT_FRAC_W - `SOFTMAX_EXP_FRAC_W)
`define SOFTMAX_FIFO_DEPTH   16

`define SOFTMAX_SLOT_IDLE       2'd0
`define SOFTMAX_SLOT_WRITE_BUSY 2'd1
`define SOFTMAX_SLOT_READ_BUSY  2'd2

`endif
